// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA32pF1RfT2mNvM9AgauuZaCijktDRd__0',
    appId: '1:553871643507:web:e8a22e33a9f31732dceb06',
    messagingSenderId: '553871643507',
    projectId: 'app-de-notas-a75a9',
    authDomain: 'app-de-notas-a75a9.firebaseapp.com',
    databaseURL: 'https://app-de-notas-a75a9-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-notas-a75a9.appspot.com',
    measurementId: 'G-EQBRRWLNVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxTOwx2SANKRl1iMW0ADavaMB6ajLA1w',
    appId: '1:553871643507:android:f6c0a998b96cc36bdceb06',
    messagingSenderId: '553871643507',
    projectId: 'app-de-notas-a75a9',
    databaseURL: 'https://app-de-notas-a75a9-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-notas-a75a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeZQpDWF2t6RirKrtswzrD-R03yTXCLtU',
    appId: '1:553871643507:ios:0a567538d53e1a5fdceb06',
    messagingSenderId: '553871643507',
    projectId: 'app-de-notas-a75a9',
    databaseURL: 'https://app-de-notas-a75a9-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-notas-a75a9.appspot.com',
    iosBundleId: 'com.example.flutterFullUxIx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeZQpDWF2t6RirKrtswzrD-R03yTXCLtU',
    appId: '1:553871643507:ios:64215567a131bf9edceb06',
    messagingSenderId: '553871643507',
    projectId: 'app-de-notas-a75a9',
    databaseURL: 'https://app-de-notas-a75a9-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-notas-a75a9.appspot.com',
    iosBundleId: 'com.example.flutterFullUxIx.RunnerTests',
  );
}
